#!/usr/bin/env python3
"""
Open3D popup viewer for ScanNet visualization outputs.

It reads PLYs generated by tools/visualize_scannet_compare.py and opens an
interactive window for visual inspection.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path
from typing import Dict, List

import numpy as np


MODE_TO_SUFFIX: Dict[str, str] = {
    "input": "input_rgb",
    "pred": "pred_sem20",
    "gt": "gt_sem20",
    "compare_input_pred": "compare_input_vs_pred",
    "compare_gt_pred": "compare_gt_vs_pred",
    "error": "pred_error_highlight",
}


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Popup visualization for custom scene results.")
    parser.add_argument("--scene", type=str, required=True, help="Scene name, e.g. custom_scene_0001")
    parser.add_argument(
        "--mode",
        type=str,
        default="compare_input_pred",
        choices=list(MODE_TO_SUFFIX.keys()) + ["all"],
        help="Which visualization to open",
    )
    parser.add_argument("--data-root", type=Path, default=Path("deploy_host/data"))
    parser.add_argument(
        "--result-dir",
        type=Path,
        default=Path("deploy_host/exp/scannet/ptv3-2080-smoke-one-scene/result"),
    )
    parser.add_argument("--vis-root", type=Path, default=Path("deploy_host/exp/vis"))
    parser.add_argument(
        "--auto-generate",
        action="store_true",
        help="Generate PLY files automatically when missing",
    )
    parser.add_argument("--width", type=int, default=1600)
    parser.add_argument("--height", type=int, default=900)
    parser.add_argument("--point-size", type=float, default=1.0)
    parser.add_argument(
        "--bg",
        type=float,
        nargs=3,
        default=[0.0, 0.0, 0.0],
        metavar=("R", "G", "B"),
        help="Background color in [0,1], default 0 0 0",
    )
    return parser


def maybe_generate_files(args: argparse.Namespace) -> None:
    scene_dir = args.vis_root / args.scene
    if scene_dir.is_dir() and any(scene_dir.glob("*.ply")):
        return
    if not args.auto_generate:
        return

    script = Path(__file__).with_name("visualize_scannet_compare.py")
    cmd = [
        sys.executable,
        str(script),
        "--data-root",
        str(args.data_root),
        "--result-dir",
        str(args.result_dir),
        "--scene",
        args.scene,
        "--output-dir",
        str(args.vis_root),
    ]
    print("[INFO] Missing PLY files. Generating via visualize_scannet_compare.py ...")
    subprocess.run(cmd, check=True)


def candidate_modes(mode: str) -> List[str]:
    if mode == "all":
        return list(MODE_TO_SUFFIX.keys())
    return [mode]


def get_ply_path(vis_root: Path, scene: str, mode: str) -> Path:
    suffix = MODE_TO_SUFFIX[mode]
    return vis_root / scene / f"{scene}_{suffix}.ply"


def open_popup(
    ply_path: Path,
    window_title: str,
    width: int,
    height: int,
    point_size: float,
    bg: List[float],
) -> None:
    try:
        import open3d as o3d
    except Exception as e:  # pragma: no cover
        raise RuntimeError(
            "Open3D is required for popup visualization. Install with: pip install open3d"
        ) from e

    pcd = o3d.io.read_point_cloud(str(ply_path))
    if pcd.is_empty():
        raise RuntimeError(f"Loaded empty point cloud: {ply_path}")

    vis = o3d.visualization.Visualizer()
    vis.create_window(window_name=window_title, width=width, height=height)
    vis.add_geometry(pcd)
    render_opt = vis.get_render_option()
    render_opt.point_size = float(point_size)
    render_opt.background_color = np.asarray(bg, dtype=np.float64)
    vis.run()
    vis.destroy_window()


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    maybe_generate_files(args)

    modes = candidate_modes(args.mode)
    found = []
    missing = []
    for mode in modes:
        p = get_ply_path(args.vis_root, args.scene, mode)
        if p.is_file():
            found.append((mode, p))
        else:
            missing.append((mode, p))

    if not found:
        msg = [
            "No visualization files found.",
            f"scene={args.scene}",
            f"vis_root={args.vis_root}",
        ]
        if missing:
            msg.append("Missing files:")
            msg.extend([f"  - {m}: {p}" for m, p in missing])
        if not args.auto_generate:
            msg.append("Tip: add --auto-generate to create files automatically.")
        raise FileNotFoundError("\n".join(msg))

    if missing:
        print("[WARN] Some modes are missing and will be skipped:")
        for mode, path in missing:
            print(f"  - {mode}: {path}")

    print(f"[INFO] Opening {len(found)} popup window(s). Close one window to continue.")
    for mode, ply_path in found:
        title = f"{args.scene} | {mode} | {ply_path.name}"
        open_popup(
            ply_path=ply_path,
            window_title=title,
            width=args.width,
            height=args.height,
            point_size=args.point_size,
            bg=args.bg,
        )


if __name__ == "__main__":
    main()
